SELECT
    (SELECT COUNT(1)
    FROM PACIENTE_SENHA_FILA PSF
    WHERE PSF.DT_GERACAO_SENHA BETWEEN TRUNC(SYSDATE, 'dd') AND FIM_DIA(SYSDATE)
        AND OBTER_LETRA_VERIFACAO_SENHA(PSF.NR_SEQ_FILA_SENHA_ORIGEM) LIKE 'U%'
        AND PSF.DT_VINCULACAO_SENHA IS NULL
        AND PSF.DT_INUTILIZACAO IS NULL) AG_TRIAJE

    , (SELECT NVL(TRUNC(MAX((SYSDATE - PSF.DT_GERACAO_SENHA)* 1440),1),0)
    FROM PACIENTE_SENHA_FILA PSF
    WHERE PSF.DT_GERACAO_SENHA BETWEEN TRUNC(SYSDATE, 'dd') AND FIM_DIA(SYSDATE)
        AND OBTER_LETRA_VERIFACAO_SENHA(PSF.NR_SEQ_FILA_SENHA_ORIGEM) LIKE 'U%'
        AND PSF.DT_VINCULACAO_SENHA IS NULL
        AND PSF.DT_INUTILIZACAO IS NULL) AG_TRIAJE_MIN

    , (SELECT COUNT(1)
    FROM TRIAGEM_PRONTO_ATEND TPA
    INNER JOIN ATENDIMENTO_PACIENTE AP ON AP.NR_ATENDIMENTO = TPA.NR_ATENDIMENTO
    INNER JOIN ATEND_PACIENTE_UNIDADE APU ON APU.NR_ATENDIMENTO = AP.NR_ATENDIMENTO
    WHERE TPA.DT_INICIO_TRIAGEM BETWEEN TRUNC(SYSDATE, 'dd') AND FIM_DIA(SYSDATE)
        AND APU.NR_SEQ_INTERNO = OBTER_ATEPACU_PACIENTE(AP.NR_ATENDIMENTO,'A')
        AND AP.IE_TIPO_ATENDIMENTO = 3
        AND AP.CD_PESSOA_FISICA NOT IN (SELECT PC.CD_PESSOA_FISICA FROM PESSOA_CLASSIF PC WHERE PC.NR_SEQ_CLASSIF = 3) -- PACIENTES PRUEBA
        AND TPA.IE_STATUS_PACIENTE <> 'P'
        AND NOT AP.DT_ATEND_MEDICO IS NULL
        AND AP.DT_FIM_CONSULTA IS NULL
        AND TPA.DT_CANCELAMENTO IS NULL
        AND AP.DT_CANCELAMENTO IS NULL) EN_CONS

    , (SELECT NVL(TRUNC(MAX((SYSDATE - AP.DT_ATEND_MEDICO) * 1440),1),0)
    FROM TRIAGEM_PRONTO_ATEND TPA
    INNER JOIN ATENDIMENTO_PACIENTE AP ON AP.NR_ATENDIMENTO = TPA.NR_ATENDIMENTO
    INNER JOIN ATEND_PACIENTE_UNIDADE APU ON APU.NR_ATENDIMENTO = AP.NR_ATENDIMENTO
    WHERE TPA.DT_INICIO_TRIAGEM BETWEEN TRUNC(SYSDATE, 'dd') AND FIM_DIA(SYSDATE)
        AND APU.NR_SEQ_INTERNO = OBTER_ATEPACU_PACIENTE(AP.NR_ATENDIMENTO,'A')
        AND AP.IE_TIPO_ATENDIMENTO = 3
        AND AP.CD_PESSOA_FISICA NOT IN (SELECT PC.CD_PESSOA_FISICA FROM PESSOA_CLASSIF PC WHERE PC.NR_SEQ_CLASSIF = 3) -- PACIENTES PRUEBA
        AND TPA.IE_STATUS_PACIENTE <> 'P'
        AND NOT AP.DT_ATEND_MEDICO IS NULL
        AND AP.DT_FIM_CONSULTA IS NULL
        AND TPA.DT_CANCELAMENTO IS NULL
        AND AP.DT_CANCELAMENTO IS NULL) EN_CONS_MIN

    , (SELECT COUNT(1)
    FROM TRIAGEM_PRONTO_ATEND TPA
    INNER JOIN ATENDIMENTO_PACIENTE AP ON AP.NR_ATENDIMENTO = TPA.NR_ATENDIMENTO
    INNER JOIN ATEND_PACIENTE_UNIDADE APU ON APU.NR_ATENDIMENTO = AP.NR_ATENDIMENTO
    WHERE TPA.DT_INICIO_TRIAGEM BETWEEN TRUNC(SYSDATE, 'dd') AND FIM_DIA(SYSDATE)
        AND APU.NR_SEQ_INTERNO = OBTER_ATEPACU_PACIENTE(AP.NR_ATENDIMENTO,'A')
        AND AP.IE_TIPO_ATENDIMENTO = 3
        AND AP.CD_PESSOA_FISICA NOT IN (SELECT PC.CD_PESSOA_FISICA FROM PESSOA_CLASSIF PC WHERE PC.NR_SEQ_CLASSIF = 3) -- PACIENTES PRUEBA
        AND TPA.IE_STATUS_PACIENTE <> 'P'
        AND AP.DT_ATEND_MEDICO IS NULL
        AND TPA.DT_CANCELAMENTO IS NULL
        AND AP.DT_CANCELAMENTO IS NULL
        AND NVL(NVL(OBTER_DESC_TRIAGEM(AP.NR_SEQ_TRIAGEM), OBTER_TRIAGEM_ATENDIMENTO(AP.NR_ATENDIMENTO)),OBTER_DESC_SEM_TRIAGEM(AP.NR_SEQ_TRIAGEM)) = 'Sin Urgente') AZUL

    , (SELECT NVL(TRUNC(MAX((SYSDATE - TPA.DT_FIM_TRIAGEM) * 1440),1),0)
    FROM TRIAGEM_PRONTO_ATEND TPA
    INNER JOIN ATENDIMENTO_PACIENTE AP ON AP.NR_ATENDIMENTO = TPA.NR_ATENDIMENTO
    INNER JOIN ATEND_PACIENTE_UNIDADE APU ON APU.NR_ATENDIMENTO = AP.NR_ATENDIMENTO
    WHERE TPA.DT_INICIO_TRIAGEM BETWEEN TRUNC(SYSDATE, 'dd') AND FIM_DIA(SYSDATE)
        AND APU.NR_SEQ_INTERNO = OBTER_ATEPACU_PACIENTE(AP.NR_ATENDIMENTO,'A')
        AND AP.IE_TIPO_ATENDIMENTO = 3
        AND AP.CD_PESSOA_FISICA NOT IN (SELECT PC.CD_PESSOA_FISICA FROM PESSOA_CLASSIF PC WHERE PC.NR_SEQ_CLASSIF = 3) -- PACIENTES PRUEBA
        AND TPA.IE_STATUS_PACIENTE <> 'P'
        AND AP.DT_ATEND_MEDICO IS NULL
        AND TPA.DT_CANCELAMENTO IS NULL
        AND AP.DT_CANCELAMENTO IS NULL
        AND NVL(NVL(OBTER_DESC_TRIAGEM(AP.NR_SEQ_TRIAGEM), OBTER_TRIAGEM_ATENDIMENTO(AP.NR_ATENDIMENTO)),OBTER_DESC_SEM_TRIAGEM(AP.NR_SEQ_TRIAGEM)) = 'Sin Urgente') AZUL_MIN

    , (SELECT COUNT(1)
    FROM TRIAGEM_PRONTO_ATEND TPA
    INNER JOIN ATENDIMENTO_PACIENTE AP ON AP.NR_ATENDIMENTO = TPA.NR_ATENDIMENTO
    INNER JOIN ATEND_PACIENTE_UNIDADE APU ON APU.NR_ATENDIMENTO = AP.NR_ATENDIMENTO
    WHERE TPA.DT_INICIO_TRIAGEM BETWEEN TRUNC(SYSDATE, 'dd') AND FIM_DIA(SYSDATE)
        AND APU.NR_SEQ_INTERNO = OBTER_ATEPACU_PACIENTE(AP.NR_ATENDIMENTO,'A')
        AND AP.IE_TIPO_ATENDIMENTO = 3
        AND AP.CD_PESSOA_FISICA NOT IN (SELECT PC.CD_PESSOA_FISICA FROM PESSOA_CLASSIF PC WHERE PC.NR_SEQ_CLASSIF = 3) -- PACIENTES PRUEBA
        AND TPA.IE_STATUS_PACIENTE <> 'P'
        AND AP.DT_ATEND_MEDICO IS NULL
        AND TPA.DT_CANCELAMENTO IS NULL
        AND AP.DT_CANCELAMENTO IS NULL
        AND NVL(NVL(OBTER_DESC_TRIAGEM(AP.NR_SEQ_TRIAGEM), OBTER_TRIAGEM_ATENDIMENTO(AP.NR_ATENDIMENTO)),OBTER_DESC_SEM_TRIAGEM(AP.NR_SEQ_TRIAGEM)) = 'Poco Urgente') VERDE

    , (SELECT NVL(TRUNC(MAX((SYSDATE - TPA.DT_FIM_TRIAGEM) * 1440),1),0)
    FROM TRIAGEM_PRONTO_ATEND TPA
    INNER JOIN ATENDIMENTO_PACIENTE AP ON AP.NR_ATENDIMENTO = TPA.NR_ATENDIMENTO
    INNER JOIN ATEND_PACIENTE_UNIDADE APU ON APU.NR_ATENDIMENTO = AP.NR_ATENDIMENTO
    WHERE TPA.DT_INICIO_TRIAGEM BETWEEN TRUNC(SYSDATE, 'dd') AND FIM_DIA(SYSDATE)
        AND APU.NR_SEQ_INTERNO = OBTER_ATEPACU_PACIENTE(AP.NR_ATENDIMENTO,'A')
        AND AP.IE_TIPO_ATENDIMENTO = 3
        AND AP.CD_PESSOA_FISICA NOT IN (SELECT PC.CD_PESSOA_FISICA FROM PESSOA_CLASSIF PC WHERE PC.NR_SEQ_CLASSIF = 3) -- PACIENTES PRUEBA
        AND TPA.IE_STATUS_PACIENTE <> 'P'
        AND AP.DT_ATEND_MEDICO IS NULL
        AND TPA.DT_CANCELAMENTO IS NULL
        AND AP.DT_CANCELAMENTO IS NULL
        AND NVL(NVL(OBTER_DESC_TRIAGEM(AP.NR_SEQ_TRIAGEM), OBTER_TRIAGEM_ATENDIMENTO(AP.NR_ATENDIMENTO)),OBTER_DESC_SEM_TRIAGEM(AP.NR_SEQ_TRIAGEM)) = 'Poco Urgente') VERDE_MIN

    , (SELECT COUNT(1)
    FROM TRIAGEM_PRONTO_ATEND TPA
    INNER JOIN ATENDIMENTO_PACIENTE AP ON AP.NR_ATENDIMENTO = TPA.NR_ATENDIMENTO
    INNER JOIN ATEND_PACIENTE_UNIDADE APU ON APU.NR_ATENDIMENTO = AP.NR_ATENDIMENTO
    WHERE TPA.DT_INICIO_TRIAGEM BETWEEN TRUNC(SYSDATE, 'dd') AND FIM_DIA(SYSDATE)
        AND APU.NR_SEQ_INTERNO = OBTER_ATEPACU_PACIENTE(AP.NR_ATENDIMENTO,'A')
        AND AP.IE_TIPO_ATENDIMENTO = 3
        AND AP.CD_PESSOA_FISICA NOT IN (SELECT PC.CD_PESSOA_FISICA FROM PESSOA_CLASSIF PC WHERE PC.NR_SEQ_CLASSIF = 3) -- PACIENTES PRUEBA
        AND TPA.IE_STATUS_PACIENTE <> 'P'
        AND AP.DT_ATEND_MEDICO IS NULL
        AND TPA.DT_CANCELAMENTO IS NULL
        AND AP.DT_CANCELAMENTO IS NULL
        AND NVL(NVL(OBTER_DESC_TRIAGEM(AP.NR_SEQ_TRIAGEM), OBTER_TRIAGEM_ATENDIMENTO(AP.NR_ATENDIMENTO)),OBTER_DESC_SEM_TRIAGEM(AP.NR_SEQ_TRIAGEM)) = 'Urgente') AMARILLO

    , (SELECT NVL(TRUNC(MAX((SYSDATE - TPA.DT_FIM_TRIAGEM) * 1440),1),0)
    FROM TRIAGEM_PRONTO_ATEND TPA
    INNER JOIN ATENDIMENTO_PACIENTE AP ON AP.NR_ATENDIMENTO = TPA.NR_ATENDIMENTO
    INNER JOIN ATEND_PACIENTE_UNIDADE APU ON APU.NR_ATENDIMENTO = AP.NR_ATENDIMENTO
    WHERE TPA.DT_INICIO_TRIAGEM BETWEEN TRUNC(SYSDATE, 'dd') AND FIM_DIA(SYSDATE)
        AND APU.NR_SEQ_INTERNO = OBTER_ATEPACU_PACIENTE(AP.NR_ATENDIMENTO,'A')
        AND AP.IE_TIPO_ATENDIMENTO = 3
        AND AP.CD_PESSOA_FISICA NOT IN (SELECT PC.CD_PESSOA_FISICA FROM PESSOA_CLASSIF PC WHERE PC.NR_SEQ_CLASSIF = 3) -- PACIENTES PRUEBA
        AND TPA.IE_STATUS_PACIENTE <> 'P'
        AND AP.DT_ATEND_MEDICO IS NULL
        AND TPA.DT_CANCELAMENTO IS NULL
        AND AP.DT_CANCELAMENTO IS NULL
        AND NVL(NVL(OBTER_DESC_TRIAGEM(AP.NR_SEQ_TRIAGEM), OBTER_TRIAGEM_ATENDIMENTO(AP.NR_ATENDIMENTO)),OBTER_DESC_SEM_TRIAGEM(AP.NR_SEQ_TRIAGEM)) = 'Urgente') AMARILLO_MIN

    , (SELECT COUNT(1)
    FROM TRIAGEM_PRONTO_ATEND TPA
    INNER JOIN ATENDIMENTO_PACIENTE AP ON AP.NR_ATENDIMENTO = TPA.NR_ATENDIMENTO
    INNER JOIN ATEND_PACIENTE_UNIDADE APU ON APU.NR_ATENDIMENTO = AP.NR_ATENDIMENTO
    WHERE TPA.DT_INICIO_TRIAGEM BETWEEN TRUNC(SYSDATE, 'dd') AND FIM_DIA(SYSDATE)
        AND APU.NR_SEQ_INTERNO = OBTER_ATEPACU_PACIENTE(AP.NR_ATENDIMENTO,'A')
        AND AP.IE_TIPO_ATENDIMENTO = 3
        AND AP.CD_PESSOA_FISICA NOT IN (SELECT PC.CD_PESSOA_FISICA FROM PESSOA_CLASSIF PC WHERE PC.NR_SEQ_CLASSIF = 3) -- PACIENTES PRUEBA
        AND TPA.IE_STATUS_PACIENTE <> 'P'
        AND AP.DT_ATEND_MEDICO IS NULL
        AND TPA.DT_CANCELAMENTO IS NULL
        AND AP.DT_CANCELAMENTO IS NULL
        AND NVL(NVL(OBTER_DESC_TRIAGEM(AP.NR_SEQ_TRIAGEM), OBTER_TRIAGEM_ATENDIMENTO(AP.NR_ATENDIMENTO)),OBTER_DESC_SEM_TRIAGEM(AP.NR_SEQ_TRIAGEM)) = 'Muy Urgente') NARANJA

    , (SELECT NVL(TRUNC(MAX((SYSDATE - TPA.DT_FIM_TRIAGEM) * 1440),1),0)
    FROM TRIAGEM_PRONTO_ATEND TPA
    INNER JOIN ATENDIMENTO_PACIENTE AP ON AP.NR_ATENDIMENTO = TPA.NR_ATENDIMENTO
    INNER JOIN ATEND_PACIENTE_UNIDADE APU ON APU.NR_ATENDIMENTO = AP.NR_ATENDIMENTO
    WHERE TPA.DT_INICIO_TRIAGEM BETWEEN TRUNC(SYSDATE, 'dd') AND FIM_DIA(SYSDATE)
        AND APU.NR_SEQ_INTERNO = OBTER_ATEPACU_PACIENTE(AP.NR_ATENDIMENTO,'A')
        AND AP.IE_TIPO_ATENDIMENTO = 3
        AND AP.CD_PESSOA_FISICA NOT IN (SELECT PC.CD_PESSOA_FISICA FROM PESSOA_CLASSIF PC WHERE PC.NR_SEQ_CLASSIF = 3) -- PACIENTES PRUEBA
        AND TPA.IE_STATUS_PACIENTE <> 'P'
        AND AP.DT_ATEND_MEDICO IS NULL
        AND TPA.DT_CANCELAMENTO IS NULL
        AND AP.DT_CANCELAMENTO IS NULL
        AND NVL(NVL(OBTER_DESC_TRIAGEM(AP.NR_SEQ_TRIAGEM), OBTER_TRIAGEM_ATENDIMENTO(AP.NR_ATENDIMENTO)),OBTER_DESC_SEM_TRIAGEM(AP.NR_SEQ_TRIAGEM)) = 'Muy Urgente') NARANJA_MIN

    , (SELECT COUNT(1)
    FROM TRIAGEM_PRONTO_ATEND TPA
    INNER JOIN ATENDIMENTO_PACIENTE AP ON AP.NR_ATENDIMENTO = TPA.NR_ATENDIMENTO
    INNER JOIN ATEND_PACIENTE_UNIDADE APU ON APU.NR_ATENDIMENTO = AP.NR_ATENDIMENTO
    WHERE TPA.DT_INICIO_TRIAGEM BETWEEN TRUNC(SYSDATE, 'dd') AND FIM_DIA(SYSDATE)
        AND APU.NR_SEQ_INTERNO = OBTER_ATEPACU_PACIENTE(AP.NR_ATENDIMENTO,'A')
        AND AP.IE_TIPO_ATENDIMENTO = 3
        AND AP.CD_PESSOA_FISICA NOT IN (SELECT PC.CD_PESSOA_FISICA FROM PESSOA_CLASSIF PC WHERE PC.NR_SEQ_CLASSIF = 3) -- PACIENTES PRUEBA
        AND TPA.IE_STATUS_PACIENTE <> 'P'
        AND AP.DT_ATEND_MEDICO IS NULL
        AND TPA.DT_CANCELAMENTO IS NULL
        AND AP.DT_CANCELAMENTO IS NULL
        AND NVL(NVL(OBTER_DESC_TRIAGEM(AP.NR_SEQ_TRIAGEM), OBTER_TRIAGEM_ATENDIMENTO(AP.NR_ATENDIMENTO)),OBTER_DESC_SEM_TRIAGEM(AP.NR_SEQ_TRIAGEM)) = 'Emergencia') ROJO

    , (SELECT NVL(TRUNC(MAX((SYSDATE - TPA.DT_FIM_TRIAGEM) * 1440),1),0)
    FROM TRIAGEM_PRONTO_ATEND TPA
    INNER JOIN ATENDIMENTO_PACIENTE AP ON AP.NR_ATENDIMENTO = TPA.NR_ATENDIMENTO
    INNER JOIN ATEND_PACIENTE_UNIDADE APU ON APU.NR_ATENDIMENTO = AP.NR_ATENDIMENTO
    WHERE TPA.DT_INICIO_TRIAGEM BETWEEN TRUNC(SYSDATE, 'dd') AND FIM_DIA(SYSDATE)
        AND APU.NR_SEQ_INTERNO = OBTER_ATEPACU_PACIENTE(AP.NR_ATENDIMENTO,'A')
        AND AP.IE_TIPO_ATENDIMENTO = 3
        AND AP.CD_PESSOA_FISICA NOT IN (SELECT PC.CD_PESSOA_FISICA FROM PESSOA_CLASSIF PC WHERE PC.NR_SEQ_CLASSIF = 3) -- PACIENTES PRUEBA
        AND TPA.IE_STATUS_PACIENTE <> 'P'
        AND AP.DT_ATEND_MEDICO IS NULL
        AND TPA.DT_CANCELAMENTO IS NULL
        AND AP.DT_CANCELAMENTO IS NULL
        AND NVL(NVL(OBTER_DESC_TRIAGEM(AP.NR_SEQ_TRIAGEM), OBTER_TRIAGEM_ATENDIMENTO(AP.NR_ATENDIMENTO)),OBTER_DESC_SEM_TRIAGEM(AP.NR_SEQ_TRIAGEM)) = 'Emergencia') ROJO_MIN

    , SYSDATE SINCRONIZADO_EN
    FROM DUAL